# GENERATED by mdb 0.1.0 from definition.yaml - edit definition.yaml and run 'mdb generate gpt_4o_mini_az_2024_07_18' instead of editing this file.
import time
import json
import logging
import os
import sys
import requests

# Requires an Azure OpenAI / Azure AI Foundry chat deployment. The model is
# addressed by its DEPLOYMENT NAME, which you choose in Azure; the API key is the
# API_KEY scoring option (a SAS Viya credential-domain entry). Where the request
# goes is decided by the container's environment - see below.
deploymentName = 'gpt-4o-mini'

# -- Azure connection: resolved from this container's ENVIRONMENT ---------------
# Where the request goes is a property of the deployment, not of the caller, so
# none of it is a scoring option. Each value resolves
#     container environment variable > the default baked into this file
# and one published image serves any subscription or project by changing its
# environment - no regeneration, rebuild or re-publish.
#
#   AZURE_OPENAI_RESOURCE     the resource/project host serving the deployment:
#                             <res>.openai.azure.com, <res>.cognitiveservices.azure.com,
#                             <res>.services.ai.azure.com, or the bare <res>
#   AZURE_OPENAI_API_VERSION  empty = the GA v1 endpoint (/openai/v1/...); a version
#                             selects the legacy /openai/deployments/<name>/... route
#                             that some resources or org policies still require
#   AZURE_OPENAI_ENDPOINT     optional full URL that replaces the built one, for a
#                             gateway in front of Azure - it must include the route
RESOURCE_ENV = 'AZURE_OPENAI_RESOURCE'
API_VERSION_ENV = 'AZURE_OPENAI_API_VERSION'
ENDPOINT_ENV = 'AZURE_OPENAI_ENDPOINT'
defaultResource = ''
defaultApiVersion = ''

def _from_env(envName, bakedDefault=''):
    "Container environment variable > baked default, trimmed; '' when neither is set."
    value = (os.environ.get(envName) or '').strip()
    return value if value else (bakedDefault or '').strip()

def _azure_endpoint(deploymentName, route):
    """The data-plane URL for one deployment; route is 'chat/completions' or 'embeddings'.

    A missing resource fails naming the variable that would have supplied it,
    rather than as a connection error against an empty host."""
    endpoint = _from_env(ENDPOINT_ENV)
    if endpoint:
        return endpoint
    host = _from_env(RESOURCE_ENV, defaultResource)
    if not host:
        raise RuntimeError(
            f"No Azure resource: set the {RESOURCE_ENV} environment variable on this "
            "container (any Azure host flavor, or the bare resource name)."
        )
    # A short resource name expands to the classic Azure OpenAI host
    if '.' not in host:
        host = f"{host}.openai.azure.com"
    apiVersion = _from_env(API_VERSION_ENV, defaultApiVersion)
    if apiVersion:
        # Legacy deployment-scoped route (deployment in the path, api-version required)
        return f"https://{host}/openai/deployments/{deploymentName}/{route}?api-version={apiVersion}"
    # GA v1 endpoint (deployment addressed via the model field in the body)
    return f"https://{host}/openai/v1/{route}"


# Initiate the logger to write output information to the log
logging.basicConfig(
    level=logging.INFO,
    handlers=[logging.StreamHandler(sys.stdout)],
    format='%(levelname)s - %(message)s'
)
logger = logging.getLogger("scoreModel")

def _parse_options(opts):
    """Parse the SCR options argument: pandas Series, list, dict or the
    pseudo-JSON string format ({key:value,key2:value2}) used by the framework."""
    if opts is None or (hasattr(opts, '__len__') and len(opts) == 0):
        return {}
    if hasattr(opts, 'iloc'):  # pandas Series
        raw = opts.iloc[0] if len(opts) > 0 else None
    else:  # list or tuple
        raw = opts[0] if len(opts) > 0 else None
    if not raw:
        return {}
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        # Try strict JSON first (must be an object - scalars fall through)
        try:
            parsed_json = json.loads(raw)
            if isinstance(parsed_json, dict):
                return parsed_json
        except Exception:
            pass
        # Fallback: parse simple k:v comma list like {key:value,key2:value2}
        parsed = {}
        s = raw.strip()
        if s.startswith('{') and s.endswith('}'):
            s = s[1:-1]
        for piece in [p for p in s.split(',') if p.strip()]:
            if ':' not in piece:
                continue
            k, v = piece.split(':', 1)
            k = k.strip().strip('"\'')
            v = v.strip().strip('"\'')
            if v.lower() in ("true", "false"):
                parsed[k] = v.lower() == "true"
            else:
                try:
                    parsed[k] = float(v) if '.' in v else int(v)
                except Exception:
                    parsed[k] = v
        return parsed
    return {}

def scoreModel(userPrompt, systemPrompt, options):
    "Output: response, run_time, prompt_length, output_length"
    started_timestamp = time.time()
    optionsDefaults = {
        "temperature": 1,
        "top_p": 1,
    }
    options = {**optionsDefaults, **_parse_options(options)}
    modelEndpoint = _azure_endpoint(deploymentName, 'chat/completions')
    payload = {
        "model": deploymentName,
        "messages": [{"role": "system", "content": systemPrompt[0]},
            {"role": "user", "content": userPrompt[0]}],
        "temperature": float(options["temperature"]),
        "top_p": float(options["top_p"]),
    }
    # Which resource this container resolved to - the one thing a shared image
    # cannot be read off the definition, and the first question when it misbehaves.
    logger.info(f"endpoint: {modelEndpoint}")
    responseObject = requests.post(
        modelEndpoint,
        headers={
            "Content-Type": "application/json",
            "api-key": options["API_KEY"],
        },
        json=payload,
        timeout=60,
    )
    try:
        responseJson = responseObject.json()
    except Exception:
        logger.error(f"Non-JSON response: {responseObject.status_code} - {responseObject.text}")
        raise
    if responseObject.status_code < 200 or responseObject.status_code >= 300:
        logger.error(f"HTTP {responseObject.status_code}: {json.dumps(responseJson)}")
        raise RuntimeError(f"Request failed: {responseObject.status_code}")
    response = responseJson['choices'][0]['message']['content']
    prompt_length = responseJson['usage']['prompt_tokens']
    output_length = responseJson['usage']['completion_tokens']
    run_time = time.time() - started_timestamp
    # Logging the response
    logger.info(f"prompt_length: {prompt_length}")
    logger.info(f"output_length: {output_length}")
    logger.info(f"run_time: {run_time}")
    logger.info(f"response: {response}")
    return response, run_time, prompt_length, output_length
