# GENERATED by mdb 0.1.0 from definition.yaml - edit definition.yaml and run 'mdb generate mistral_small_32' instead of editing this file.
import time
import json
import logging
import sys
import requests

modelVersion = 'mistral-small-latest'
modelEndpoint = 'https://api.mistral.ai/v1/chat/completions'

# Initiate the logger to write output information to the log
logging.basicConfig(
    level=logging.INFO,
    handlers=[logging.StreamHandler(sys.stdout)],
    format='%(levelname)s - %(message)s'
)
logger = logging.getLogger("scoreModel")

def _scalar(value):
    """The one value behind an SCR input, whatever the caller's convention.

    CAS / DATA step and the SCR container hand each input over as a
    one-element list (or pandas Series); the MAS REST API hands over the plain
    string. A str also answers len() and [0], so indexing it does not fail - it
    silently keeps the first character, and "What is SAS Viya?" is scored as
    "W". Normalise once, here, and never index an input again."""
    if value is None:
        return ''
    if isinstance(value, (str, bytes, dict)):
        return value
    if hasattr(value, 'iloc'):  # pandas Series
        return value.iloc[0] if len(value) > 0 else ''
    if isinstance(value, (list, tuple)):
        return value[0] if len(value) > 0 else ''
    return value

def _parse_options(opts):
    """Parse the SCR options argument: pandas Series, list, dict or the
    pseudo-JSON string format ({key:value,key2:value2}) used by the framework."""
    raw = _scalar(opts)
    if raw is None or raw == '' or (hasattr(raw, '__len__') and len(raw) == 0):
        return {}
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, bytes):
        raw = raw.decode('utf-8', 'replace')
    if isinstance(raw, str):
        # Try strict JSON first (must be an object - scalars fall through)
        try:
            parsed_json = json.loads(raw)
            if isinstance(parsed_json, dict):
                return parsed_json
        except Exception:
            pass
        # Fallback: parse simple k:v comma list like {key:value,key2:value2}
        parsed = {}
        s = raw.strip()
        if s.startswith('{') and s.endswith('}'):
            s = s[1:-1]
        for piece in [p for p in s.split(',') if p.strip()]:
            if ':' not in piece:
                continue
            k, v = piece.split(':', 1)
            k = k.strip().strip('"\'')
            v = v.strip().strip('"\'')
            if v.lower() in ("true", "false"):
                parsed[k] = v.lower() == "true"
            else:
                try:
                    parsed[k] = float(v) if '.' in v else int(v)
                except Exception:
                    parsed[k] = v
        return parsed
    return {}

def scoreModel(userPrompt, systemPrompt, options):
    "Output: response, run_time, prompt_length, output_length"
    started_timestamp = time.time()
    # One value per input, whatever the caller's convention: CAS/SCR pass
    # one-element lists, the MAS REST API passes plain strings - and a str
    # indexed with [0] silently becomes its first character.
    userPrompt, systemPrompt = _scalar(userPrompt), _scalar(systemPrompt)
    optionsDefaults = {
        "temperature": 1,
        "top_p": 1,
        "max_tokens": 1000,
    }
    options = {**optionsDefaults, **_parse_options(options)}
    payload = {
        "model": modelVersion,
        "messages": [{"role": "system", "content": systemPrompt},
            {"role": "user", "content": userPrompt}],
        "temperature": float(options["temperature"]),
        "top_p": float(options["top_p"]),
        "max_tokens": int(options["max_tokens"]),
    }
    responseObject = requests.post(
        modelEndpoint,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {options['API_KEY']}",
        },
        json=payload,
        timeout=60,
    )
    try:
        responseJson = responseObject.json()
    except Exception:
        logger.error(f"Non-JSON response: {responseObject.status_code} - {responseObject.text}")
        raise
    if responseObject.status_code < 200 or responseObject.status_code >= 300:
        logger.error(f"HTTP {responseObject.status_code}: {json.dumps(responseJson)}")
        raise RuntimeError(f"Request failed: {responseObject.status_code}")
    response = responseJson['choices'][0]['message']['content']
    prompt_length = responseJson['usage']['prompt_tokens']
    output_length = responseJson['usage']['completion_tokens']
    run_time = time.time() - started_timestamp
    # Logging the response
    logger.info(f"prompt_length: {prompt_length}")
    logger.info(f"output_length: {output_length}")
    logger.info(f"run_time: {run_time}")
    logger.info(f"response: {response}")
    return response, run_time, prompt_length, output_length
