# GENERATED by mdb 2.2.0 from definition.yaml - edit definition.yaml and run 'mdb generate clef_flash' instead of editing this file.
import time
import json
import logging
import sys
import requests

modelVersion = 'cloudflare/clef-flash'
modelEndpoint = 'https://openrouter.ai/api/v1/systemone'

# Initiate the logger to write output information to the log
logging.basicConfig(
    level=logging.INFO,
    handlers=[logging.StreamHandler(sys.stdout)],
    format='%(levelname)s - %(message)s'
)
logger = logging.getLogger("scoreModel")

def _scalar(value):
    """The one value behind an SCR input, whatever the caller's convention.

    CAS / DATA step and the SCR container hand each input over as a
    one-element list (or pandas Series); the MAS REST API hands over the plain
    string. A str also answers len() and [0], so indexing it does not fail - it
    silently keeps the first character, and "What is SAS Viya?" is scored as
    "W". Normalise once, here, and never index an input again."""
    if value is None:
        return ''
    if isinstance(value, (str, bytes, dict)):
        return value
    if hasattr(value, 'iloc'):  # pandas Series
        return value.iloc[0] if len(value) > 0 else ''
    if hasattr(value, '__len__') and hasattr(value, '__getitem__'):
        # list, tuple, numpy array, ...: whatever answered [0] before still does
        return value[0] if len(value) > 0 else ''
    return value

def _parse_options(opts):
    """Parse the SCR options argument: pandas Series, list, dict or the
    pseudo-JSON string format ({key:value,key2:value2}) used by the framework."""
    raw = _scalar(opts)
    if raw is None or raw == '' or (hasattr(raw, '__len__') and len(raw) == 0):
        return {}
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, bytes):
        raw = raw.decode('utf-8', 'replace')
    if isinstance(raw, str):
        # Try strict JSON first (must be an object - scalars fall through)
        try:
            parsed_json = json.loads(raw)
            if isinstance(parsed_json, dict):
                return parsed_json
        except Exception:
            pass
        # Fallback: parse simple k:v comma list like {key:value,key2:value2}
        parsed = {}
        s = raw.strip()
        if s.startswith('{') and s.endswith('}'):
            s = s[1:-1]
        for piece in [p for p in s.split(',') if p.strip()]:
            if ':' not in piece:
                continue
            k, v = piece.split(':', 1)
            k = k.strip().strip('"\'')
            v = v.strip().strip('"\'')
            if v.lower() in ("true", "false"):
                parsed[k] = v.lower() == "true"
            else:
                try:
                    parsed[k] = float(v) if '.' in v else int(v)
                except Exception:
                    parsed[k] = v
        return parsed
    return {}

def _state_value(state):
    # A state that parses as a JSON object or array is sent as structured
    # data (the model reads field names); anything else is sent as text.
    try:
        parsed = json.loads(state)
        return parsed if isinstance(parsed, (dict, list)) else state
    except Exception:
        return state


def _headline(answer):
    # The first question's answer as a branch node reads it: the chosen
    # option, the score, or yes/no for a noul - with the confidence beside it.
    kind = answer.get("type")
    if kind == "noul":
        probability = float(answer.get("noul", 0.0))
        return ("yes" if probability >= 0.5 else "no"), (probability if probability >= 0.5 else 1.0 - probability)
    if kind == "score":
        return str(answer.get("score", "")), float(answer.get("confidence", 0.0))
    return str(answer.get("choice", "")), float(answer.get("confidence", 0.0))


def scoreModel(state, questions, options):
    "Output: answers, answer, confidence, run_time, prompt_length, output_length"
    started_timestamp = time.time()
    # One value per input, whatever the caller's convention: CAS/SCR pass
    # one-element lists, the MAS REST API passes plain strings - and a str
    # indexed with [0] silently becomes its first character.
    state, questions = _scalar(state), _scalar(questions)
    optionsDefaults = {

    }
    options = {**optionsDefaults, **_parse_options(options)}
    # The System One request: the state once, every question beside it. The
    # questions arrive verbatim in the provider's own shape, so a new question
    # type needs no change here.
    payload = {
        "model": modelVersion,
        "state": _state_value(state),
        "questions": json.loads(questions),
    }
    responseObject = requests.post(
        modelEndpoint,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {options['API_KEY']}",
        },
        json=payload,
        timeout=60,
    )
    try:
        responseJson = responseObject.json()
    except Exception:
        logger.error(f"Non-JSON response: {responseObject.status_code} - {responseObject.text}")
        raise
    if responseObject.status_code < 200 or responseObject.status_code >= 300:
        logger.error(f"HTTP {responseObject.status_code}: {json.dumps(responseJson)}")
        raise RuntimeError(f"Request failed: {responseObject.status_code}")
    answersObject = responseJson.get('answers') or {}
    firstAnswer = next(iter(answersObject.values()), {}) if isinstance(answersObject, dict) else {}
    answer, confidence = _headline(firstAnswer)
    answers = json.dumps(answersObject)
    usage = responseJson.get('usage') or {}
    prompt_length = usage.get('input_tokens', 0)
    # A decision model generates no text; the field stays for the shared usage report.
    output_length = usage.get('output_tokens', 0)
    run_time = time.time() - started_timestamp
    # Logging the response
    logger.info(f"prompt_length: {prompt_length}")
    logger.info(f"output_length: {output_length}")
    logger.info(f"run_time: {run_time}")
    logger.info(f"answer: {answer} ({confidence:.3f})")
    logger.info(f"answers: {answers}")
    return answers, answer, confidence, run_time, prompt_length, output_length
