# GENERATED by mdb 0.1.0 from definition.yaml - edit definition.yaml and run 'mdb generate azure_openai_env' instead of editing this file.
import time
import json
import logging
import os
import sys
import requests

# Azure OpenAI / Azure AI Foundry, configured by the container's ENVIRONMENT.
#
# Nothing that binds this model to one subscription is a scoring input. On top
# of the connection variables every Azure definition reads (further down), this
# one also takes the key and the deployment name from the environment:
#
#   AZURE_OPENAI_API_KEY     the key - never baked into this file, and not a
#                            required scoring input (no API_KEY option). A caller
#                            that passes API_KEY anyway still wins, so a
#                            credential-domain caller keeps working unchanged.
#   AZURE_OPENAI_DEPLOYMENT  the deployment name - what Azure calls the model;
#                            blank uses the default below
#
# so ONE published image serves any Azure deployment: re-point a container by
# changing its environment, with no regeneration, rebuild or re-publish. A
# missing value fails with the variable named, rather than as an opaque 401/404.
API_KEY_ENV = 'AZURE_OPENAI_API_KEY'
DEPLOYMENT_ENV = 'AZURE_OPENAI_DEPLOYMENT'
defaultDeploymentName = 'gpt-5.6-luna'

# -- Azure connection: resolved from this container's ENVIRONMENT ---------------
# Where the request goes is a property of the deployment, not of the caller, so
# none of it is a scoring option. Each value resolves
#     container environment variable > the default baked into this file
# and one published image serves any subscription or project by changing its
# environment - no regeneration, rebuild or re-publish.
#
#   AZURE_OPENAI_RESOURCE     the resource/project host serving the deployment:
#                             <res>.openai.azure.com, <res>.cognitiveservices.azure.com,
#                             <res>.services.ai.azure.com, or the bare <res>
#   AZURE_OPENAI_API_VERSION  empty = the GA v1 endpoint (/openai/v1/...); a version
#                             selects the legacy /openai/deployments/<name>/... route
#                             that some resources or org policies still require. A
#                             v1-only resource answers that route with a bare 401 -
#                             leave the version empty there.
#   AZURE_OPENAI_ENDPOINT     optional full URL that replaces the built one, for a
#                             gateway in front of Azure - it must include the route
RESOURCE_ENV = 'AZURE_OPENAI_RESOURCE'
API_VERSION_ENV = 'AZURE_OPENAI_API_VERSION'
ENDPOINT_ENV = 'AZURE_OPENAI_ENDPOINT'
defaultResource = ''
defaultApiVersion = ''

def _from_env(envName, bakedDefault=''):
    "Container environment variable > baked default, trimmed; '' when neither is set."
    value = (os.environ.get(envName) or '').strip()
    return value if value else (bakedDefault or '').strip()

def _azure_endpoint(deploymentName, route):
    """The data-plane URL for one deployment; route is 'chat/completions' or 'embeddings'.

    A missing resource fails naming the variable that would have supplied it,
    rather than as a connection error against an empty host."""
    endpoint = _from_env(ENDPOINT_ENV)
    if endpoint:
        return endpoint
    host = _from_env(RESOURCE_ENV, defaultResource)
    if not host:
        raise RuntimeError(
            f"No Azure resource: set the {RESOURCE_ENV} environment variable on this "
            "container (any Azure host flavor, or the bare resource name)."
        )
    # A short resource name expands to the classic Azure OpenAI host
    if '.' not in host:
        host = f"{host}.openai.azure.com"
    apiVersion = _from_env(API_VERSION_ENV, defaultApiVersion)
    if apiVersion:
        # Legacy deployment-scoped route (deployment in the path, api-version required)
        return f"https://{host}/openai/deployments/{deploymentName}/{route}?api-version={apiVersion}"
    # GA v1 endpoint (deployment addressed via the model field in the body)
    return f"https://{host}/openai/v1/{route}"


# Initiate the logger to write output information to the log
logging.basicConfig(
    level=logging.INFO,
    handlers=[logging.StreamHandler(sys.stdout)],
    format='%(levelname)s - %(message)s'
)
logger = logging.getLogger("scoreModel")

def _scalar(value):
    """The one value behind an SCR input, whatever the caller's convention.

    CAS / DATA step and the SCR container hand each input over as a
    one-element list (or pandas Series); the MAS REST API hands over the plain
    string. A str also answers len() and [0], so indexing it does not fail - it
    silently keeps the first character, and "What is SAS Viya?" is scored as
    "W". Normalise once, here, and never index an input again."""
    if value is None:
        return ''
    if isinstance(value, (str, bytes, dict)):
        return value
    if hasattr(value, 'iloc'):  # pandas Series
        return value.iloc[0] if len(value) > 0 else ''
    if isinstance(value, (list, tuple)):
        return value[0] if len(value) > 0 else ''
    return value

def _parse_options(opts):
    """Parse the SCR options argument: pandas Series, list, dict or the
    pseudo-JSON string format ({key:value,key2:value2}) used by the framework."""
    raw = _scalar(opts)
    if raw is None or raw == '' or (hasattr(raw, '__len__') and len(raw) == 0):
        return {}
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, bytes):
        raw = raw.decode('utf-8', 'replace')
    if isinstance(raw, str):
        # Try strict JSON first (must be an object - scalars fall through)
        try:
            parsed_json = json.loads(raw)
            if isinstance(parsed_json, dict):
                return parsed_json
        except Exception:
            pass
        # Fallback: parse simple k:v comma list like {key:value,key2:value2}
        parsed = {}
        s = raw.strip()
        if s.startswith('{') and s.endswith('}'):
            s = s[1:-1]
        for piece in [p for p in s.split(',') if p.strip()]:
            if ':' not in piece:
                continue
            k, v = piece.split(':', 1)
            k = k.strip().strip('"\'')
            v = v.strip().strip('"\'')
            if v.lower() in ("true", "false"):
                parsed[k] = v.lower() == "true"
            else:
                try:
                    parsed[k] = float(v) if '.' in v else int(v)
                except Exception:
                    parsed[k] = v
        return parsed
    return {}

def scoreModel(userPrompt, systemPrompt, options):
    "Output: response, run_time, prompt_length, output_length"
    started_timestamp = time.time()
    # One value per input, whatever the caller's convention: CAS/SCR pass
    # one-element lists, the MAS REST API passes plain strings - and a str
    # indexed with [0] silently becomes its first character.
    userPrompt, systemPrompt = _scalar(userPrompt), _scalar(systemPrompt)
    optionsDefaults = {
        "reasoning_effort": "medium",
        "max_completion_tokens": 4000,
    }
    options = {**optionsDefaults, **_parse_options(options)}
    # An explicitly passed key wins; a blank one is 'not set', not an override -
    # UIs send empty strings for controls the user left alone.
    apiKey = str(options.get("API_KEY") or '').strip() or _from_env(API_KEY_ENV)
    if not apiKey:
        raise RuntimeError(
            f"No Azure API key: set the {API_KEY_ENV} environment variable on this container."
        )
    deploymentName = _from_env(DEPLOYMENT_ENV, defaultDeploymentName)
    if not deploymentName:
        raise RuntimeError(
            f"No Azure deployment: set the {DEPLOYMENT_ENV} environment variable on this container."
        )
    modelEndpoint = _azure_endpoint(deploymentName, 'chat/completions')
    payload = {
        "model": deploymentName,
        "messages": [{"role": "system", "content": systemPrompt},
            {"role": "user", "content": userPrompt}],
        "reasoning_effort": {"minimal": "none", "low": "low", "medium": "medium", "high": "high", "maximum": "xhigh"}.get(str(options["reasoning_effort"]), "medium"),
        "max_completion_tokens": int(options["max_completion_tokens"]),
    }
    # Which deployment this container resolved to - the one thing a shared image
    # cannot be read off the definition, and the first question when it misbehaves.
    logger.info(f"endpoint: {modelEndpoint}")
    responseObject = requests.post(
        modelEndpoint,
        headers={
            "Content-Type": "application/json",
            "api-key": apiKey,
        },
        json=payload,
        timeout=60,
    )
    try:
        responseJson = responseObject.json()
    except Exception:
        logger.error(f"Non-JSON response: {responseObject.status_code} - {responseObject.text}")
        raise
    if responseObject.status_code < 200 or responseObject.status_code >= 300:
        logger.error(f"HTTP {responseObject.status_code}: {json.dumps(responseJson)}")
        raise RuntimeError(f"Request failed: {responseObject.status_code}")
    response = responseJson['choices'][0]['message']['content']
    prompt_length = responseJson['usage']['prompt_tokens']
    output_length = responseJson['usage']['completion_tokens']
    run_time = time.time() - started_timestamp
    # Logging the response
    logger.info(f"prompt_length: {prompt_length}")
    logger.info(f"output_length: {output_length}")
    logger.info(f"run_time: {run_time}")
    logger.info(f"response: {response}")
    return response, run_time, prompt_length, output_length
