# GENERATED by mdb 0.1.0 from definition.yaml - edit definition.yaml and run 'mdb generate embedding_gemma_300m' instead of editing this file.
import time
import json
import logging
import sys
import os
from sentence_transformers import SentenceTransformer

# Set the transformer cache directory to a writable directory
os.environ['TRANSFORMERS_CACHE'] = '/pybox/model'

checkpoint = './embedding_gemma_300m'
model = SentenceTransformer(checkpoint)

# Initiate the logger to write output information to the log
logging.basicConfig(
    level=logging.INFO,
    handlers=[logging.StreamHandler(sys.stdout)],
    format='%(levelname)s - %(message)s'
)
logger = logging.getLogger("scoreModel")

def _parse_options(opts):
    """Parse the SCR options argument: pandas Series, list, dict or the
    pseudo-JSON string format ({key:value,key2:value2}) used by the framework."""
    if opts is None or (hasattr(opts, '__len__') and len(opts) == 0):
        return {}
    if hasattr(opts, 'iloc'):  # pandas Series
        raw = opts.iloc[0] if len(opts) > 0 else None
    else:  # list or tuple
        raw = opts[0] if len(opts) > 0 else None
    if not raw:
        return {}
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        # Try strict JSON first
        try:
            return json.loads(raw)
        except Exception:
            pass
        # Fallback: parse simple k:v comma list like {key:value,key2:value2}
        parsed = {}
        s = raw.strip()
        if s.startswith('{') and s.endswith('}'):
            s = s[1:-1]
        for piece in [p for p in s.split(',') if p.strip()]:
            if ':' not in piece:
                continue
            k, v = piece.split(':', 1)
            k = k.strip().strip('"\'')
            v = v.strip().strip('"\'')
            if v.lower() in ("true", "false"):
                parsed[k] = v.lower() == "true"
            else:
                try:
                    parsed[k] = float(v) if '.' in v else int(v)
                except Exception:
                    parsed[k] = v
        return parsed
    return {}

def scoreModel(document, project, options):
    "Output: embedding, run_time, tokens"
    started_timestamp = time.time()
    optionsDefaults = {
        "Embedding_Mode": "query",
    }
    options = {**optionsDefaults, **_parse_options(options)}
    if options.get('Embedding_Mode') == 'document':
        embeddingObject = model.encode_document(document[0])
    else:
        embeddingObject = model.encode_query(document[0])
    embedding = json.dumps(embeddingObject.tolist())
    tokens = model.tokenize([document[0]])['input_ids'].size(dim=1) - 2
    run_time = time.time() - started_timestamp
    # Logging the response
    logger.info(f"project: {project[0]}")
    logger.info(f"tokens: {tokens}")
    logger.info(f"run_time: {run_time}")
    return embedding, run_time, tokens
