# GENERATED by mdb 0.1.0 from definition.yaml - edit definition.yaml and run 'mdb generate gemini_flash_25' instead of editing this file.
import time
import json
import logging
import sys
import requests

modelVersion = 'gemini-2.5-flash'
modelEndpoint = f"https://generativelanguage.googleapis.com/v1beta/models/{modelVersion}:generateContent"

# Initiate the logger to write output information to the log
logging.basicConfig(
    level=logging.INFO,
    handlers=[logging.StreamHandler(sys.stdout)],
    format='%(levelname)s - %(message)s'
)
logger = logging.getLogger("scoreModel")

def _parse_options(opts):
    """Parse the SCR options argument: pandas Series, list, dict or the
    pseudo-JSON string format ({key:value,key2:value2}) used by the framework."""
    if opts is None or (hasattr(opts, '__len__') and len(opts) == 0):
        return {}
    if hasattr(opts, 'iloc'):  # pandas Series
        raw = opts.iloc[0] if len(opts) > 0 else None
    else:  # list or tuple
        raw = opts[0] if len(opts) > 0 else None
    if not raw:
        return {}
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        # Try strict JSON first (must be an object - scalars fall through)
        try:
            parsed_json = json.loads(raw)
            if isinstance(parsed_json, dict):
                return parsed_json
        except Exception:
            pass
        # Fallback: parse simple k:v comma list like {key:value,key2:value2}
        parsed = {}
        s = raw.strip()
        if s.startswith('{') and s.endswith('}'):
            s = s[1:-1]
        for piece in [p for p in s.split(',') if p.strip()]:
            if ':' not in piece:
                continue
            k, v = piece.split(':', 1)
            k = k.strip().strip('"\'')
            v = v.strip().strip('"\'')
            if v.lower() in ("true", "false"):
                parsed[k] = v.lower() == "true"
            else:
                try:
                    parsed[k] = float(v) if '.' in v else int(v)
                except Exception:
                    parsed[k] = v
        return parsed
    return {}

def scoreModel(userPrompt, systemPrompt, options):
    "Output: response, run_time, prompt_length, output_length"
    started_timestamp = time.time()
    optionsDefaults = {
        "temperature": 1,
        "top_k": 40,
        "top_p": 0.95,
        "max_tokens": 256,
    }
    options = {**optionsDefaults, **_parse_options(options)}
    payload = {
        "system_instruction": {"parts": [{"text": systemPrompt[0]}]},
        "contents": [{"parts": [{"text": userPrompt[0]}]}],
        "generationConfig": {
            "temperature": float(options["temperature"]),
            "topK": int(options["top_k"]),
            "topP": float(options["top_p"]),
            "maxOutputTokens": int(options["max_tokens"]),
        },
    }
    responseObject = requests.post(
        modelEndpoint,
        headers={
            "Content-Type": "application/json",
            "x-goog-api-key": options["API_KEY"],
        },
        json=payload,
        timeout=60,
    )
    try:
        responseJson = responseObject.json()
    except Exception:
        logger.error(f"Non-JSON response: {responseObject.status_code} - {responseObject.text}")
        raise
    if responseObject.status_code < 200 or responseObject.status_code >= 300:
        logger.error(f"HTTP {responseObject.status_code}: {json.dumps(responseJson)}")
        raise RuntimeError(f"Request failed: {responseObject.status_code}")
    candidateContent = responseJson["candidates"][0].get("content", {})
    response = "".join(
        part["text"] for part in candidateContent.get("parts", []) if "text" in part
    )
    prompt_length = responseJson['usageMetadata']['promptTokenCount']
    output_length = responseJson['usageMetadata'].get('candidatesTokenCount', 0)
    run_time = time.time() - started_timestamp
    # Logging the response
    logger.info(f"prompt_length: {prompt_length}")
    logger.info(f"output_length: {output_length}")
    logger.info(f"run_time: {run_time}")
    logger.info(f"response: {response}")
    return response, run_time, prompt_length, output_length
